In [1]:
import pandas as pd
import numpy as np
import os, sys

In [23]:
pred_1_fp = '../../results-agg/clst-IS2017-1-repacked/predictive-output.csv'
pred_2_fp = '../../results-agg/clst-IS2017-2-repacked/predictive-output.csv'

pred_1_df = pd.read_csv(pred_1_fp)
pred_2_df = pd.read_csv(pred_2_fp)

In [21]:
(pred_1_df['model'] + '-' + pred_1_df['log']).unique()

array([nan, 'P272-L31', 'P272-L62', 'P285-L13', 'P285-L56', 'P291-L51',
       'P291-L22', 'P284-L34', 'P284-L48', 'P275-L1', 'P275-L52',
       'P241-L50', 'P241-L37', 'P246-L10', 'P246-L49'], dtype=object)

In [22]:
(pred_2_df['model'] + '-' + pred_2_df['log']).unique()

array([nan, 'P381-L63', 'P381-L4', 'P383-L61', 'P383-L16', 'P430-L19',
       'P430-L57', 'P313-L59', 'P313-L25', 'P347-L58', 'P436-L54',
       'P307-L53'], dtype=object)

In [24]:
(pred_1_df['model'] + '-' + pred_1_df['log']).unique()

array([nan, 'P272-L31', 'P272-L62', 'P284-L34', 'P284-L48', 'P246-L49',
       'P246-L10', 'P241-L50', 'P241-L37', 'P285-L56', 'P285-L13',
       'P291-L22', 'P291-L51', 'P275-L1', 'P275-L52'], dtype=object)

In [25]:
(pred_2_df['model'] +t '-' + pred_2_df['log']).unique()

array([nan, 'P436-L54', 'P436-L46', 'P383-L16', 'P383-L61', 'P430-L19',
       'P430-L57', 'P297-L7', 'P297-L55', 'P347-L58', 'P347-L40',
       'P313-L59', 'P313-L25', 'P381-L4', 'P381-L63', 'P307-L28',
       'P307-L53'], dtype=object)